/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Business;
import Business.GridOperator.ConsumerTransaction;
import Business.Profiles.ConsumerRepresentativeProfile.ConsumerRepresentativeProfile;
import Business.Users.UserAccount;
import Business.Utils.ChartUtils;
import Business.Utils.ForecastingUtil;
import Business.Utils.TableExporter;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;
import java.net.URL;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author udayk
 */
public class ConsumerDBJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConsumerDBJPanel
     */
    Business business;
    
    JPanel cardLayout;
    
    UserAccount user;
    
    ConsumerRepresentativeProfile crp;
    
    UUID currentlyEditingPolicyId;
    
    UUID updateComplianceId;
    private Image originalImage;
    
    public ConsumerDBJPanel(JPanel cardLayout, Business business, UserAccount user) {
        initComponents();
        this.cardLayout = cardLayout;
        this.business = business;
        this.user = user;
        this.crp = business.getCrp().findConsumerRepresentative(user.getPersonId());
        jLabel2.setText(user.getProfile().getPerson().getName());
        populateBillTable();
        populateoverview();
        try {
            URL imageURL = getClass().getResource("/images/C.png");
            if (imageURL != null) {
                originalImage = ImageIO.read(imageURL);
            } else {
                System.err.println("Image not found");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Add a component listener to resize the image when the JLabel is resized
        img1.addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent e) {
                resizeImage();
            }
        });
    }
    
    private void resizeImage() {
        if (originalImage != null) {
            // Resize the image to the current size of the JLabel
            Image resizedImage = originalImage.getScaledInstance(img1.getWidth(), img1.getHeight(), Image.SCALE_SMOOTH);

            // Update the icon of the JLabel
            ImageIcon icon = new ImageIcon(resizedImage);
            img1.setIcon(icon);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        TopPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BottomTabPane = new javax.swing.JTabbedPane();
        Overview = new javax.swing.JPanel();
        lblEnergyProcured = new javax.swing.JLabel();
        lblEnergyProcuredVal = new javax.swing.JLabel();
        lblAmountSpent = new javax.swing.JLabel();
        lblAmountSpentVal = new javax.swing.JLabel();
        Forecasting = new javax.swing.JPanel();
        lblFromDate = new javax.swing.JLabel();
        jDateChooserFromDate = new com.toedter.calendar.JDateChooser();
        lblToDate = new javax.swing.JLabel();
        jDateChooserToDate = new com.toedter.calendar.JDateChooser();
        btnForecast = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableForcast = new javax.swing.JTable();
        btnExport1 = new javax.swing.JButton();
        ForcastingChart = new javax.swing.JPanel();
        MarketPlace = new javax.swing.JPanel();
        MarketPlaceTabbedPane = new javax.swing.JTabbedPane();
        EnergyCart = new javax.swing.JPanel();
        lblAmt1 = new javax.swing.JLabel();
        txtAmt1 = new javax.swing.JTextField();
        lblComments2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaComments2 = new javax.swing.JTextArea();
        btnSubmit2 = new javax.swing.JButton();
        lblDate2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        lblAmt2 = new javax.swing.JLabel();
        txtAmt2 = new javax.swing.JTextField();
        TransactionHistory = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        btnExport3 = new javax.swing.JButton();
        btnRefresh3 = new javax.swing.JButton();
        Help1 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtDescription1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        img1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(1000, 600));

        TopPane.setBackground(new java.awt.Color(255, 255, 255));
        TopPane.setPreferredSize(new java.awt.Dimension(1000, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Consumer");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        jLabel2.setText("Name");

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(java.awt.Color.white);
        btnBack.setText("logout");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Settings");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopPaneLayout = new javax.swing.GroupLayout(TopPane);
        TopPane.setLayout(TopPaneLayout);
        TopPaneLayout.setHorizontalGroup(
            TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 624, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap())
        );
        TopPaneLayout.setVerticalGroup(
            TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPaneLayout.createSequentialGroup()
                .addGroup(TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopPaneLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(jButton2)))
                    .addGroup(TopPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(TopPane);

        BottomTabPane.setBackground(new java.awt.Color(255, 255, 255));

        Overview.setBackground(new java.awt.Color(255, 255, 255));

        lblEnergyProcured.setText("Total Energy Procured");

        lblEnergyProcuredVal.setBackground(new java.awt.Color(153, 255, 255));
        lblEnergyProcuredVal.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblEnergyProcuredVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnergyProcuredVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblAmountSpent.setText("Total Amount Spent");

        lblAmountSpentVal.setBackground(new java.awt.Color(153, 255, 255));
        lblAmountSpentVal.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblAmountSpentVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmountSpentVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout OverviewLayout = new javax.swing.GroupLayout(Overview);
        Overview.setLayout(OverviewLayout);
        OverviewLayout.setHorizontalGroup(
            OverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OverviewLayout.createSequentialGroup()
                .addGroup(OverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OverviewLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblEnergyProcuredVal, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(lblAmountSpentVal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OverviewLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lblEnergyProcured)
                        .addGap(290, 290, 290)
                        .addComponent(lblAmountSpent)))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        OverviewLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAmountSpentVal, lblEnergyProcuredVal});

        OverviewLayout.setVerticalGroup(
            OverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnergyProcured, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmountSpent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEnergyProcuredVal, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(lblAmountSpentVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        BottomTabPane.addTab("Overveiw", Overview);

        Forecasting.setBackground(new java.awt.Color(255, 255, 255));

        lblFromDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFromDate.setText("From Date");

        lblToDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblToDate.setText("To Date");

        btnForecast.setBackground(new java.awt.Color(0, 0, 0));
        btnForecast.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnForecast.setForeground(new java.awt.Color(255, 255, 255));
        btnForecast.setText("Forecast");
        btnForecast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForecastActionPerformed(evt);
            }
        });

        jTableForcast.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Forecasted Production"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableForcast.setMaximumSize(new java.awt.Dimension(291, 400));
        jScrollPane4.setViewportView(jTableForcast);

        btnExport1.setBackground(new java.awt.Color(0, 0, 0));
        btnExport1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExport1.setForeground(new java.awt.Color(255, 255, 255));
        btnExport1.setText("Export");
        btnExport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExport1ActionPerformed(evt);
            }
        });

        ForcastingChart.setBackground(new java.awt.Color(255, 255, 255));
        ForcastingChart.setMaximumSize(new java.awt.Dimension(500, 400));
        ForcastingChart.setPreferredSize(new java.awt.Dimension(500, 400));

        javax.swing.GroupLayout ForcastingChartLayout = new javax.swing.GroupLayout(ForcastingChart);
        ForcastingChart.setLayout(ForcastingChartLayout);
        ForcastingChartLayout.setHorizontalGroup(
            ForcastingChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        ForcastingChartLayout.setVerticalGroup(
            ForcastingChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ForecastingLayout = new javax.swing.GroupLayout(Forecasting);
        Forecasting.setLayout(ForecastingLayout);
        ForecastingLayout.setHorizontalGroup(
            ForecastingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForecastingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ForecastingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ForecastingLayout.createSequentialGroup()
                        .addComponent(lblFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnForecast)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExport1))
                    .addGroup(ForecastingLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ForcastingChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        ForecastingLayout.setVerticalGroup(
            ForecastingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForecastingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ForecastingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ForecastingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnForecast)
                        .addComponent(btnExport1)))
                .addGap(24, 24, 24)
                .addGroup(ForecastingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(ForcastingChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        BottomTabPane.addTab("Forecasting", Forecasting);

        MarketPlace.setBackground(new java.awt.Color(255, 255, 255));

        MarketPlaceTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        MarketPlaceTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        EnergyCart.setBackground(new java.awt.Color(255, 255, 255));

        lblAmt1.setBackground(new java.awt.Color(192, 221, 250));
        lblAmt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAmt1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAmt1.setText("Quantity of Energy (MWh)");

        lblComments2.setBackground(new java.awt.Color(192, 221, 250));
        lblComments2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComments2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblComments2.setText("Comments (If any)");

        jScrollPane5.setBackground(new java.awt.Color(192, 221, 250));

        txtAreaComments2.setColumns(20);
        txtAreaComments2.setRows(5);
        jScrollPane5.setViewportView(txtAreaComments2);

        btnSubmit2.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit2.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit2.setText("Submit");
        btnSubmit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit2ActionPerformed(evt);
            }
        });

        lblDate2.setBackground(new java.awt.Color(192, 221, 250));
        lblDate2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDate2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDate2.setText("Date");

        lblAmt2.setBackground(new java.awt.Color(192, 221, 250));
        lblAmt2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAmt2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAmt2.setText("Price");

        javax.swing.GroupLayout EnergyCartLayout = new javax.swing.GroupLayout(EnergyCart);
        EnergyCart.setLayout(EnergyCartLayout);
        EnergyCartLayout.setHorizontalGroup(
            EnergyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnergyCartLayout.createSequentialGroup()
                .addGroup(EnergyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnergyCartLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(EnergyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(EnergyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnergyCartLayout.createSequentialGroup()
                                    .addComponent(lblAmt2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtAmt2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(EnergyCartLayout.createSequentialGroup()
                                    .addComponent(lblAmt1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtAmt1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EnergyCartLayout.createSequentialGroup()
                                .addComponent(lblDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EnergyCartLayout.createSequentialGroup()
                                .addComponent(lblComments2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(EnergyCartLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnSubmit2)))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        EnergyCartLayout.setVerticalGroup(
            EnergyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnergyCartLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(EnergyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnergyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnergyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmt2)
                    .addComponent(txtAmt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnergyCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComments2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit2)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        MarketPlaceTabbedPane.addTab("Energy Cart", EnergyCart);

        TransactionHistory.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bill ID", "Quantity Bought", "Amount", "Date"
            }
        ));
        jScrollPane7.setViewportView(jTable4);

        btnExport3.setBackground(new java.awt.Color(0, 0, 0));
        btnExport3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExport3.setForeground(new java.awt.Color(255, 255, 255));
        btnExport3.setText("Export");

        btnRefresh3.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh3.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh3.setText("Refresh");

        javax.swing.GroupLayout TransactionHistoryLayout = new javax.swing.GroupLayout(TransactionHistory);
        TransactionHistory.setLayout(TransactionHistoryLayout);
        TransactionHistoryLayout.setHorizontalGroup(
            TransactionHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionHistoryLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(TransactionHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TransactionHistoryLayout.createSequentialGroup()
                        .addComponent(btnExport3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh3))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        TransactionHistoryLayout.setVerticalGroup(
            TransactionHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionHistoryLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransactionHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExport3)
                    .addComponent(btnRefresh3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MarketPlaceTabbedPane.addTab("Transaction History", TransactionHistory);

        javax.swing.GroupLayout MarketPlaceLayout = new javax.swing.GroupLayout(MarketPlace);
        MarketPlace.setLayout(MarketPlaceLayout);
        MarketPlaceLayout.setHorizontalGroup(
            MarketPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarketPlaceLayout.createSequentialGroup()
                .addComponent(MarketPlaceTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MarketPlaceLayout.setVerticalGroup(
            MarketPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MarketPlaceTabbedPane)
        );

        BottomTabPane.addTab("EnergyMart", MarketPlace);

        Help1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane5.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane5.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setText("Issue raised By ");

        txtDescription1.setColumns(20);
        txtDescription1.setRows(5);
        jScrollPane13.setViewportView(txtDescription1);

        jLabel16.setText("Description of Issue");

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane13)
                            .addComponent(jTextField6)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jButton5)))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Submit Issue", jPanel8);

        javax.swing.GroupLayout Help1Layout = new javax.swing.GroupLayout(Help1);
        Help1.setLayout(Help1Layout);
        Help1Layout.setHorizontalGroup(
            Help1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        Help1Layout.setVerticalGroup(
            Help1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );

        BottomTabPane.addTab("Help", Help1);

        jSplitPane1.setRightComponent(BottomTabPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateoverview(){
        
        lblEnergyProcuredVal.setText(String.valueOf(business.getGridData().findTotalConsumptionByConsumerId(crp.getCd().getConsumerID())));
        lblAmountSpentVal.setText(String.valueOf(business.getGridData().findTotalConsumptionByConsumerId(crp.getCd().getConsumerID())));
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        cardLayout.remove(this);
        CardLayout layout = (CardLayout) cardLayout.getLayout();
        layout.previous(cardLayout);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AccInfoUpdateJPanel accCreationPanel = new AccInfoUpdateJPanel(cardLayout, business, user);
        cardLayout.add("AccInfoUpdateJPanel", accCreationPanel);
        CardLayout layout = (CardLayout) cardLayout.getLayout();
        layout.next(cardLayout);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSubmit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit2ActionPerformed
        // Parse the date from dateField
        Date date = jDateChooser2.getDate();
        LocalDateTime dateTime = LocalDateTime.ofInstant(date.toInstant(), ZoneId.systemDefault());
        // Parse the quantity of energy
        double quantity = Double.parseDouble(txtAmt1.getText()); // You'll need to handle NumberFormatException
        double price = Double.parseDouble(txtAmt2.getText());
        // Get the comments
        String comments = txtAreaComments2.getText();

        // Create a new EnergyTransaction object
        // Replace EnergyTransaction with your actual transaction class

        if(business.getGridData().calculateTotalEnergyProcured()-business.getGridData().calculateTotalEnergyConsumered()-quantity>0){
            business.getGridData().addCt( new ConsumerTransaction(crp.getCd().getConsumerID(), quantity, price, comments, dateTime));
            System.out.println(business.getGridData().getCt().size());
            JOptionPane.showMessageDialog(this, "Energy transaction submitted successfully.");
            populateBillTable();
            return;
        }

        // Display confirmation message
        JOptionPane.showMessageDialog(this, "Please try less amount, totla energy available "+ (business.getGridData().calculateTotalEnergyProcured()-business.getGridData().calculateTotalEnergyConsumered()));
    }//GEN-LAST:event_btnSubmit2ActionPerformed

    private void btnExport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExport1ActionPerformed

        TableExporter.exportToCSV(jTableForcast, this);
    }//GEN-LAST:event_btnExport1ActionPerformed

    private void btnForecastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForecastActionPerformed

        // Forecast future production based on the average
        LocalDate startDate = jDateChooserFromDate.getDate().toInstant()
        .atZone(ZoneId.systemDefault())
        .toLocalDate(); // get start date from "From Date" date chooser

        LocalDate endDate = jDateChooserToDate.getDate().toInstant()
        .atZone(ZoneId.systemDefault())
        .toLocalDate();// get end date from "To Date" date chooser

        Map<LocalDate, Double> m  = ForecastingUtil.forecastConsumerDemand(business.getGridData().getCt(), crp.getCd().getConsumerID(), startDate, endDate);
        JFreeChart chart = ChartUtils.createLineChart(m);

        // Create a panel to display the chart
        ChartPanel chartPanel = new ChartPanel(chart);
        // Assuming 'this' is a JPanel, you add the chartPanel to it
        ForcastingChart.removeAll();
        ForcastingChart.setLayout(new BorderLayout());
        ForcastingChart.add(chartPanel, BorderLayout.CENTER);

        // Revalidate and repaint to ensure the chart is displayed
        ForcastingChart.revalidate();
        ForcastingChart.repaint();

        // Display the forecast in the table
        populateForecastTable(m);
    }//GEN-LAST:event_btnForecastActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String raised = jTextField6.getText();
        String Des = txtDescription1.getText();

        business.getTpd().add(Des, raised);
        JOptionPane.showMessageDialog(this, "Issue reported succusfully");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed


    private void populateBillTable() {
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        model.setRowCount(0); // Clear existing data

        List<ConsumerTransaction> ct = business.getGridData().getCt(); // This method needs to retrieve your bill data

        for (ConsumerTransaction bill : ct) {
            if(bill.getConsumerId().equals(crp.getCd().getConsumerID())){
                Object[] row = new Object[4];
                row[0] = bill.getTransactionId();
                row[2] = bill.getPrice();
                row[3] = bill.getDate();
                row[1] = bill.getQuantityOfEnergy();
                model.addRow(row);
            }
        }
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BottomTabPane;
    private javax.swing.JPanel EnergyCart;
    private javax.swing.JPanel ForcastingChart;
    private javax.swing.JPanel Forecasting;
    private javax.swing.JPanel Help1;
    private javax.swing.JPanel MarketPlace;
    private javax.swing.JTabbedPane MarketPlaceTabbedPane;
    private javax.swing.JPanel Overview;
    private javax.swing.JPanel TopPane;
    private javax.swing.JPanel TransactionHistory;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExport1;
    private javax.swing.JButton btnExport3;
    private javax.swing.JButton btnForecast;
    private javax.swing.JButton btnRefresh3;
    private javax.swing.JButton btnSubmit2;
    private javax.swing.JLabel img1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooserFromDate;
    private com.toedter.calendar.JDateChooser jDateChooserToDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTableForcast;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblAmountSpent;
    private javax.swing.JLabel lblAmountSpentVal;
    private javax.swing.JLabel lblAmt1;
    private javax.swing.JLabel lblAmt2;
    private javax.swing.JLabel lblComments2;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblEnergyProcured;
    private javax.swing.JLabel lblEnergyProcuredVal;
    private javax.swing.JLabel lblFromDate;
    private javax.swing.JLabel lblToDate;
    private javax.swing.JTextField txtAmt1;
    private javax.swing.JTextField txtAmt2;
    private javax.swing.JTextArea txtAreaComments2;
    private javax.swing.JTextArea txtDescription1;
    // End of variables declaration//GEN-END:variables

    private void populateForecastTable(Map<LocalDate, Double> m) {
        DefaultTableModel model = (DefaultTableModel) jTableForcast.getModel();
        model.setRowCount(0); // Clear existing data

        for (Map.Entry<LocalDate, Double> entry : m.entrySet()) {
            LocalDate date = entry.getKey();
            Double value = entry.getValue();
            Object[] row = new Object[2];
                row[0] = date;
                row[1] = value;
            model.addRow(row);
        }
        
    }
}
