/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author udayk
 */
public class IEODBJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IEODBJPanel
     */
    
    private Image originalImage;
    public IEODBJPanel() {
        initComponents();
        try {
            URL imageURL = getClass().getResource("/images/IEO.png");
            if (imageURL != null) {
                originalImage = ImageIO.read(imageURL);
            } else {
                System.err.println("Image not found");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Add a component listener to resize the image when the JLabel is resized
        img1.addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent e) {
                resizeImage();
            }
        });
        
    }
    
    private void resizeImage() {
        if (originalImage != null) {
            // Resize the image to the current size of the JLabel
            Image resizedImage = originalImage.getScaledInstance(img1.getWidth(), img1.getHeight(), Image.SCALE_SMOOTH);

            // Update the icon of the JLabel
            ImageIcon icon = new ImageIcon(resizedImage);
            img1.setIcon(icon);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        TopPane = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        Settings = new javax.swing.JButton();
        GOp = new javax.swing.JLabel();
        GridOperatorName = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        EnergyData = new javax.swing.JPanel();
        EnergyDataTabbedPane = new javax.swing.JTabbedPane();
        ProductionReport = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        btnExport3 = new javax.swing.JButton();
        ConsumptionReport = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        btnExport5 = new javax.swing.JButton();
        Forecast = new javax.swing.JPanel();
        jDateChooser7 = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jDateChooser8 = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        Graphs = new javax.swing.JPanel();
        Graph2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Policies = new javax.swing.JPanel();
        PoliciesTabbedPane = new javax.swing.JTabbedPane();
        ViewPolicy = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        btnExport1 = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnRecommend = new javax.swing.JButton();
        Recommendation = new javax.swing.JPanel();
        lblSearchPolicy = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        lblReco = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtReco = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        txtSearchPolicy = new javax.swing.JTextField();
        lblPolicyDesc = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtPolicyDesc = new javax.swing.JTextArea();
        lblPolicyName = new javax.swing.JLabel();
        txtPolicyName = new javax.swing.JTextField();
        Help = new javax.swing.JPanel();
        HelpTabbedPane = new javax.swing.JTabbedPane();
        SubmitIssue = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        History = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        img1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(1000, 600));
        jSplitPane1.setMinimumSize(new java.awt.Dimension(1000, 600));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1000, 600));

        TopPane.setBackground(new java.awt.Color(255, 255, 255));

        Back.setBackground(new java.awt.Color(0, 0, 0));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");

        Settings.setBackground(new java.awt.Color(0, 0, 0));
        Settings.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Settings.setForeground(new java.awt.Color(255, 255, 255));
        Settings.setText("Settings");

        GOp.setBackground(new java.awt.Color(255, 255, 255));
        GOp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GOp.setText("INTERNATIONAL ENERGY ORGANISATION");

        GridOperatorName.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        GridOperatorName.setText("Name");

        javax.swing.GroupLayout TopPaneLayout = new javax.swing.GroupLayout(TopPane);
        TopPane.setLayout(TopPaneLayout);
        TopPaneLayout.setHorizontalGroup(
            TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GridOperatorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Settings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Back)
                .addGap(43, 43, 43))
        );
        TopPaneLayout.setVerticalGroup(
            TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GOp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Settings)
                        .addComponent(Back)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GridOperatorName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(TopPane);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        EnergyData.setBackground(new java.awt.Color(255, 255, 255));

        EnergyDataTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        EnergyDataTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        ProductionReport.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Energy Producer", "Source of Energy", "Quantity Procured"
            }
        ));
        jScrollPane6.setViewportView(jTable4);

        btnExport3.setBackground(new java.awt.Color(0, 0, 0));
        btnExport3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExport3.setForeground(new java.awt.Color(255, 255, 255));
        btnExport3.setText("Export");

        javax.swing.GroupLayout ProductionReportLayout = new javax.swing.GroupLayout(ProductionReport);
        ProductionReport.setLayout(ProductionReportLayout);
        ProductionReportLayout.setHorizontalGroup(
            ProductionReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductionReportLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ProductionReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExport3)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        ProductionReportLayout.setVerticalGroup(
            ProductionReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductionReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExport3)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        EnergyDataTabbedPane.addTab("Production", ProductionReport);

        ConsumptionReport.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane12.setBackground(new java.awt.Color(255, 255, 255));

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Consumers", "Energy Consumption"
            }
        ));
        jScrollPane12.setViewportView(jTable9);

        btnExport5.setBackground(new java.awt.Color(0, 0, 0));
        btnExport5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExport5.setForeground(new java.awt.Color(255, 255, 255));
        btnExport5.setText("Export");

        javax.swing.GroupLayout ConsumptionReportLayout = new javax.swing.GroupLayout(ConsumptionReport);
        ConsumptionReport.setLayout(ConsumptionReportLayout);
        ConsumptionReportLayout.setHorizontalGroup(
            ConsumptionReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsumptionReportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsumptionReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExport5)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        ConsumptionReportLayout.setVerticalGroup(
            ConsumptionReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsumptionReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExport5)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        EnergyDataTabbedPane.addTab("Consumption", ConsumptionReport);

        Forecast.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("From Date");

        jLabel19.setText("To Date");

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Forecast");

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Forecasted Production"
            }
        ));
        jScrollPane5.setViewportView(jTable7);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("View as Graphs");

        jLabel20.setText("Production Forecast");

        jLabel21.setText("Consumption Forecast");

        jScrollPane11.setBackground(new java.awt.Color(255, 255, 255));

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Forecasted Consumption"
            }
        ));
        jScrollPane11.setViewportView(jTable8);

        javax.swing.GroupLayout ForecastLayout = new javax.swing.GroupLayout(Forecast);
        Forecast.setLayout(ForecastLayout);
        ForecastLayout.setHorizontalGroup(
            ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForecastLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ForecastLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7))
                    .addGroup(ForecastLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ForecastLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        ForecastLayout.setVerticalGroup(
            ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForecastLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        EnergyDataTabbedPane.addTab("ForeCast", Forecast);

        Graphs.setBackground(new java.awt.Color(255, 255, 255));

        Graph2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        Graph2.addTab("Graphs1", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        Graph2.addTab("Graphs2", jPanel1);

        javax.swing.GroupLayout GraphsLayout = new javax.swing.GroupLayout(Graphs);
        Graphs.setLayout(GraphsLayout);
        GraphsLayout.setHorizontalGroup(
            GraphsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Graph2)
        );
        GraphsLayout.setVerticalGroup(
            GraphsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Graph2)
        );

        EnergyDataTabbedPane.addTab("Graphs", Graphs);

        javax.swing.GroupLayout EnergyDataLayout = new javax.swing.GroupLayout(EnergyData);
        EnergyData.setLayout(EnergyDataLayout);
        EnergyDataLayout.setHorizontalGroup(
            EnergyDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(EnergyDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EnergyDataTabbedPane))
        );
        EnergyDataLayout.setVerticalGroup(
            EnergyDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
            .addGroup(EnergyDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EnergyDataTabbedPane))
        );

        jTabbedPane1.addTab("Energy Data", EnergyData);

        Policies.setBackground(new java.awt.Color(255, 255, 255));

        PoliciesTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        PoliciesTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        ViewPolicy.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane13.setBackground(new java.awt.Color(255, 255, 255));

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Policy ID", "Policy Name", "Effective Date", "End Date", "Status"
            }
        ));
        jScrollPane13.setViewportView(jTable10);

        btnExport1.setBackground(new java.awt.Color(0, 0, 0));
        btnExport1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExport1.setForeground(new java.awt.Color(255, 255, 255));
        btnExport1.setText("Export");
        btnExport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExport1ActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(0, 0, 0));
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnRecommend.setBackground(new java.awt.Color(0, 0, 0));
        btnRecommend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRecommend.setForeground(new java.awt.Color(255, 255, 255));
        btnRecommend.setText("Recommend");
        btnRecommend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecommendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewPolicyLayout = new javax.swing.GroupLayout(ViewPolicy);
        ViewPolicy.setLayout(ViewPolicyLayout);
        ViewPolicyLayout.setHorizontalGroup(
            ViewPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPolicyLayout.createSequentialGroup()
                .addGroup(ViewPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ViewPolicyLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExport1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecommend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnView))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ViewPolicyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ViewPolicyLayout.setVerticalGroup(
            ViewPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPolicyLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnRecommend)
                    .addComponent(btnExport1))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        PoliciesTabbedPane.addTab("View", ViewPolicy);

        Recommendation.setBackground(new java.awt.Color(255, 255, 255));

        lblSearchPolicy.setText("Search Policies");

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");

        lblReco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReco.setText("Recommendations");

        txtReco.setColumns(20);
        txtReco.setRows(5);
        jScrollPane3.setViewportView(txtReco);

        btnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");

        lblPolicyDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPolicyDesc.setText("Policy Description");

        txtPolicyDesc.setColumns(20);
        txtPolicyDesc.setRows(5);
        jScrollPane9.setViewportView(txtPolicyDesc);

        lblPolicyName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPolicyName.setText("Policy Name");

        javax.swing.GroupLayout RecommendationLayout = new javax.swing.GroupLayout(Recommendation);
        Recommendation.setLayout(RecommendationLayout);
        RecommendationLayout.setHorizontalGroup(
            RecommendationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecommendationLayout.createSequentialGroup()
                .addGroup(RecommendationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RecommendationLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(RecommendationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecommendationLayout.createSequentialGroup()
                                .addComponent(lblReco)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecommendationLayout.createSequentialGroup()
                                .addGroup(RecommendationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblPolicyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPolicyDesc))
                                .addGap(18, 18, 18)
                                .addGroup(RecommendationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(RecommendationLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btnSubmit))
                    .addGroup(RecommendationLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(lblSearchPolicy)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)))
                .addContainerGap(255, Short.MAX_VALUE))
        );

        RecommendationLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane3, jScrollPane9});

        RecommendationLayout.setVerticalGroup(
            RecommendationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecommendationLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(RecommendationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchPolicy)
                    .addComponent(btnSearch)
                    .addComponent(txtSearchPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RecommendationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPolicyName)
                    .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RecommendationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolicyDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RecommendationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReco)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        RecommendationLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane3, jScrollPane9});

        PoliciesTabbedPane.addTab("Recommendation", Recommendation);

        javax.swing.GroupLayout PoliciesLayout = new javax.swing.GroupLayout(Policies);
        Policies.setLayout(PoliciesLayout);
        PoliciesLayout.setHorizontalGroup(
            PoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PoliciesTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        PoliciesLayout.setVerticalGroup(
            PoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PoliciesTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Policies", Policies);

        Help.setBackground(new java.awt.Color(255, 255, 255));

        HelpTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        HelpTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        SubmitIssue.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Date");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane8.setViewportView(txtDescription);

        jLabel11.setText("Description of Issue");

        jButton3.setText("Submit");

        javax.swing.GroupLayout SubmitIssueLayout = new javax.swing.GroupLayout(SubmitIssue);
        SubmitIssue.setLayout(SubmitIssueLayout);
        SubmitIssueLayout.setHorizontalGroup(
            SubmitIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubmitIssueLayout.createSequentialGroup()
                .addGroup(SubmitIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubmitIssueLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(SubmitIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(SubmitIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8)
                            .addComponent(jDateChooser5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(SubmitIssueLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jButton3)))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        SubmitIssueLayout.setVerticalGroup(
            SubmitIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubmitIssueLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(SubmitIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jDateChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SubmitIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        HelpTabbedPane.addTab("Submit an Issue", SubmitIssue);

        History.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Issue ID", "Date Submitted", "Description of Issue", "Response"
            }
        ));
        jScrollPane7.setViewportView(jTable5);

        javax.swing.GroupLayout HistoryLayout = new javax.swing.GroupLayout(History);
        History.setLayout(HistoryLayout);
        HistoryLayout.setHorizontalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HistoryLayout.setVerticalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HelpTabbedPane.addTab("History", History);

        javax.swing.GroupLayout HelpLayout = new javax.swing.GroupLayout(Help);
        Help.setLayout(HelpLayout);
        HelpLayout.setHorizontalGroup(
            HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HelpTabbedPane)
        );
        HelpLayout.setVerticalGroup(
            HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HelpTabbedPane)
        );

        jTabbedPane1.addTab("Help", Help);

        jSplitPane1.setRightComponent(jTabbedPane1);

        img1.setBackground(new java.awt.Color(255, 0, 153));
        img1.setForeground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExport1ActionPerformed
        //TableExporter.exportToCSV(jTable2, this);
    }//GEN-LAST:event_btnExport1ActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        //int selectedRow = jTable2.getSelectedRow();

//        if (selectedRow >= 0) {
//            // Assuming policy details are in the following order:
//            // Policy ID, Policy Name, Effective Date, End Date, Status, Description
//            Policy policy = (Policy) jTable2.getModel().getValueAt(selectedRow, 0);
//
//            // Populate the update form fields
//            txtPolicyName.setText(policy.getPolicyName());
//            LocalDate localDate = policy.getEffectiveDate();
//            Instant instant = localDate.atStartOfDay(ZoneId.systemDefault()).toInstant();
//            Date date = Date.from(instant);
//
//            jDateChooser3.setDate(date);
//
//            LocalDate localDate1 = policy.getEndDate();
//            Instant instant1 = localDate1.atStartOfDay(ZoneId.systemDefault()).toInstant();
//            Date date1 = Date.from(instant1);
//            jDateChooser4.setDate(date1);
//            txtPolicyDesc.setText(policy.getDescription());
//
//            currentlyEditingPolicyId = policy.getPolicyID();
//
//            // Switch to the update tab
//            jTabbedPane2.setSelectedIndex(2); // Replace UPDATE_TAB_INDEX with actual index of update tab
//        } else {
//            JOptionPane.showMessageDialog(null, "Please select a policy to update.");
//        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRecommendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecommendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecommendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPanel ConsumptionReport;
    private javax.swing.JPanel EnergyData;
    private javax.swing.JTabbedPane EnergyDataTabbedPane;
    private javax.swing.JPanel Forecast;
    private javax.swing.JLabel GOp;
    private javax.swing.JTabbedPane Graph2;
    private javax.swing.JPanel Graphs;
    private javax.swing.JLabel GridOperatorName;
    private javax.swing.JPanel Help;
    private javax.swing.JTabbedPane HelpTabbedPane;
    private javax.swing.JPanel History;
    private javax.swing.JPanel Policies;
    private javax.swing.JTabbedPane PoliciesTabbedPane;
    private javax.swing.JPanel ProductionReport;
    private javax.swing.JPanel Recommendation;
    private javax.swing.JButton Settings;
    private javax.swing.JPanel SubmitIssue;
    private javax.swing.JPanel TopPane;
    private javax.swing.JPanel ViewPolicy;
    private javax.swing.JButton btnExport1;
    private javax.swing.JButton btnExport3;
    private javax.swing.JButton btnExport5;
    private javax.swing.JButton btnRecommend;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel img1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private com.toedter.calendar.JDateChooser jDateChooser7;
    private com.toedter.calendar.JDateChooser jDateChooser8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JLabel lblPolicyDesc;
    private javax.swing.JLabel lblPolicyName;
    private javax.swing.JLabel lblReco;
    private javax.swing.JLabel lblSearchPolicy;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextArea txtPolicyDesc;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextArea txtReco;
    private javax.swing.JTextField txtSearchPolicy;
    // End of variables declaration//GEN-END:variables
}
