/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Business;
import Business.Users.UserAccount;
import Business.Users.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;
import java.net.URL;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author udayk
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    Business business;
    
    JPanel cardLayout;
    
    private Image originalImage;

    public LoginJPanel(JPanel cardLayout, Business business) {
        initComponents();
        this.cardLayout = cardLayout;
        this.business = business;
        try {
            URL imageURL = getClass().getResource("/images/GMSW.png");
            if (imageURL != null) {
                originalImage = ImageIO.read(imageURL);
            } else {
                System.err.println("Image not found");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Add a component listener to resize the image when the JLabel is resized
        jLabel1.addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent e) {
                resizeImage();
            }
        });
    }

    private void resizeImage() {
        if (originalImage != null) {
            // Resize the image to the current size of the JLabel
            Image resizedImage = originalImage.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);

            // Update the icon of the JLabel
            ImageIcon icon = new ImageIcon(resizedImage);
            jLabel1.setIcon(icon);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelUserName = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        labelUserName1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblNewUser = new javax.swing.JLabel();
        btnSignup = new javax.swing.JButton();
        lblhide = new javax.swing.JLabel();
        lblvisible = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        labelUserName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelUserName.setText("User name");
        labelUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        labelUserName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelUserName1.setText("Password");
        labelUserName1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblNewUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewUser.setText("New User?");

        btnSignup.setBackground(new java.awt.Color(0, 0, 0));
        btnSignup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Sign-up");
        btnSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignupMouseExited(evt);
            }
        });
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        lblhide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png"))); // NOI18N
        lblhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblhideMousePressed(evt);
            }
        });

        lblvisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visible.png"))); // NOI18N
        lblvisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblvisibleMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignup))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnLogin))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblvisible, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblhide, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(labelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhide, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblvisible, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(293, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed

    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(Color.red);
        btnLogin.setForeground(Color.black);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setForeground(Color.white);
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        
        UserAccountDirectory uad = business.getUserAcconts();
        UserAccount useraccount = uad.AuthenticateUser(username, password);
        try {
//            if(!twoFactor(useraccount.getPerson().getEmail())){
//                return;
//            }
                if (useraccount == null) {
                    JOptionPane.showMessageDialog(this, "Invalid credentials, Please use correct username and pass");
                    return;
                }else{
                    System.out.println("Login success for "+username);
                    if(useraccount.isEnabled()){
                        if(useraccount.getAssociatedPersonProfile().getRole().equals("Energy Producer")){
                            
                            EnergyProducerDBJPanel panel = new EnergyProducerDBJPanel(cardLayout, business, useraccount);
                            cardLayout.add("EnergyProducerDBJPanel", panel);
                            CardLayout layout = (CardLayout) cardLayout.getLayout();
                            layout.next(cardLayout);
                        }else if(useraccount.getAssociatedPersonProfile().getRole().equals("Govt Reg")){
                            
                            GovtAgencyDBJPanel panel = new GovtAgencyDBJPanel(cardLayout, business, useraccount);
                            cardLayout.add("GovtAgencyDBJPanel", panel);
                            CardLayout layout = (CardLayout) cardLayout.getLayout();
                            layout.next(cardLayout);
                        }else if(useraccount.getAssociatedPersonProfile().getRole().equals("Grid Operator")){
                            
                            GridOperatorDBJPanel panel = new GridOperatorDBJPanel(cardLayout, business, useraccount);
                            cardLayout.add("GridOperatorDBJPanel", panel);
                            CardLayout layout = (CardLayout) cardLayout.getLayout();
                            layout.next(cardLayout);
                        }else if(useraccount.getAssociatedPersonProfile().getRole().equals("Consumer")){
                            
                            ConsumerDBJPanel panel = new ConsumerDBJPanel(cardLayout, business, useraccount);
                            cardLayout.add("ConsumerDBJPanel", panel);
                            CardLayout layout = (CardLayout) cardLayout.getLayout();
                            layout.next(cardLayout);
                        }else if(useraccount.getAssociatedPersonProfile().getRole().equals("INTERNATIONAL ENERGY ORGANISATION")){
                            
                            ResearchOrganisationDBJPanel panel = new ResearchOrganisationDBJPanel(cardLayout, business, useraccount);
                            cardLayout.add("IEO", panel);
                            CardLayout layout = (CardLayout) cardLayout.getLayout();
                            layout.next(cardLayout);
                        }else if(useraccount.getAssociatedPersonProfile().getRole().equals("NGO")){
                            
                            ResearchOrganisationDBJPanel panel = new ResearchOrganisationDBJPanel(cardLayout, business, useraccount);
                            cardLayout.add("NGO", panel);
                            CardLayout layout = (CardLayout) cardLayout.getLayout();
                            layout.next(cardLayout);
                        }else if(useraccount.getAssociatedPersonProfile().getRole().equals("Research Analyst")){
                            
                            ResearchOrganisationDBJPanel panel = new ResearchOrganisationDBJPanel(cardLayout, business, useraccount);
                            cardLayout.add("Research", panel);
                            CardLayout layout = (CardLayout) cardLayout.getLayout();
                            layout.next(cardLayout);
                        }else if(useraccount.getAssociatedPersonProfile().getRole().equals("Technology Provider")){
                            
                            TechnologyProviderJPanel panel = new TechnologyProviderJPanel(cardLayout, business, useraccount);
                            cardLayout.add("TechnologyProviderJPanel", panel);
                            CardLayout layout = (CardLayout) cardLayout.getLayout();
                            layout.next(cardLayout);
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Users is blocked!");
                    }
                }
        } catch (Exception ex) {
            Logger.getLogger(LoginJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseEntered
        // TODO add your handling code here:
        btnSignup.setBackground(Color.red);
        btnSignup.setForeground(Color.black);
    }//GEN-LAST:event_btnSignupMouseEntered

    private void btnSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseExited
        // TODO add your handling code here:
        btnSignup.setBackground(new java.awt.Color(0, 0, 0));
        btnSignup.setForeground(Color.white);
    }//GEN-LAST:event_btnSignupMouseExited

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        AccCreationJPanel accCreationPanel = new AccCreationJPanel(cardLayout, business);
        cardLayout.add("AccCreationJPanel", accCreationPanel);
        CardLayout layout = (CardLayout) cardLayout.getLayout();
        layout.next(cardLayout);
    }//GEN-LAST:event_btnSignupActionPerformed

    private void lblhideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhideMousePressed
        // TODO add your handling code here:
        lblhide.setVisible(false);
        lblvisible.setVisible(true);
        txtPassword.setEchoChar((char)0);
    }//GEN-LAST:event_lblhideMousePressed

    private void lblvisibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvisibleMousePressed
        // TODO add your handling code here:
        lblvisible.setVisible(false);
        lblhide.setVisible(true);
        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_lblvisibleMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JLabel labelUserName1;
    private javax.swing.JLabel lblNewUser;
    private javax.swing.JLabel lblhide;
    private javax.swing.JLabel lblvisible;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

       private String generateVerificationCode() {
        Random random = new Random();
        return String.format("%04d", random.nextInt(10000)); // generates a 4 digit code
    }
    private boolean twoFactor(String email) throws Exception {
       String verificationCode = generateVerificationCode();
        
        
        
       EmailSender.sendEmail(
            "gregms.final@hotmail.com", // Your Hotmail email address
            "gregmsfinal0806",         // Your Hotmail password or app password
            email,         // Recipient's email address
            "GREGMS Verification Code",                  // Email subject
            "Your verification code is: " + verificationCode  // Email body
        );
        // Prompt user to enter the verification code
        String inputCode = JOptionPane.showInputDialog(this, "Enter the verification code sent to your email:",
                "Verification", JOptionPane.PLAIN_MESSAGE);
        // Check if the codes match
        if (verificationCode.equals(inputCode)) {
            // Proceed with user creation
            JOptionPane.showMessageDialog(this, "Verification successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            return true;
        } else {
            // Handle incorrect verification code
            JOptionPane.showMessageDialog(this, "Verification failed! Incorrect code.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
}
