/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Business;
import Business.EnergyProvider.EnergyData;
import Business.EnergyProvider.EnergyProducer;
import Business.GridOperator.ConsumerTransaction;
import Business.Profiles.ConsumerRepresentativeProfile.ConsumerRepresentativeProfile;
import Business.Profiles.TechnologyProvider.TechnologyProviderProfile;
import Business.TechnologyProvider.HelpRequest;
import Business.Users.UserAccount;
import Business.Utils.ChartUtils;
import Business.Utils.ForecastingUtil;
import Business.Utils.Transaction;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;
import java.net.URL;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author udayk
 */
public class TechnologyProviderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TechnologyProviderJPanel
     */
    Business business;
    
    JPanel cardLayout;
    
    UserAccount user;
    
    TechnologyProviderProfile tpp;
    
    UUID currentlyEditingPolicyId;
    
    UUID updateComplianceId;
    
    private Image originalImage;
        
    JPanel containerPanel = new JPanel();
    
    public TechnologyProviderJPanel(JPanel cardLayout, Business business, UserAccount user) {
        initComponents();
        this.cardLayout = cardLayout;
        this.business = business;
        this.user = user;
        this.tpp = business.getTp().findTechnologyProvider(user.getPersonId());
        GridOperatorName.setText(user.getAssociatedPersonProfile().getPerson().getName());
        populatePieGraph();
        gridDashboard();
        populateManageTable(business.getUserAcconts().getUserAccountList());
        populateHelpRequestsTable(jTable1, business.getTpd().getHelpRequests());
        populateConsumedTable();
        populateProcuredTable();
        
        
        try {
            URL imageURL = getClass().getResource("/images/Tech Provider.png");
            if (imageURL != null) {
                originalImage = ImageIO.read(imageURL);
            } else {
                System.err.println("Image not found");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Add a component listener to resize the image when the JLabel is resized
        img1.addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent e) {
                resizeImage();
            }
        });

    }
    
    private void resizeImage() {
        if (originalImage != null) {
            // Resize the image to the current size of the JLabel
            Image resizedImage = originalImage.getScaledInstance(img1.getWidth(), img1.getHeight(), Image.SCALE_SMOOTH);

            // Update the icon of the JLabel
            ImageIcon icon = new ImageIcon(resizedImage);
            img1.setIcon(icon);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        GOp = new javax.swing.JLabel();
        GridOperatorName = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        DashBoard = new javax.swing.JPanel();
        lblEnergyProducers = new javax.swing.JLabel();
        lblEnergyProducersVal = new javax.swing.JLabel();
        lblEnergyProd = new javax.swing.JLabel();
        lblEnergyProdVal = new javax.swing.JLabel();
        lblConsumers = new javax.swing.JLabel();
        lblConsumersVal = new javax.swing.JLabel();
        lblConsumptionVal = new javax.swing.JLabel();
        lblConsumption = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Support = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Reports = new javax.swing.JPanel();
        ReportsTabbedPane = new javax.swing.JTabbedPane();
        ProductionReport = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        btnExport3 = new javax.swing.JButton();
        ConsumptionReport = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        btnExport5 = new javax.swing.JButton();
        Forecast = new javax.swing.JPanel();
        jDateChooser7 = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jDateChooser8 = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        Graphs = new javax.swing.JPanel();
        Graph2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        ManageUsers = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableUsers = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        lblPersonID = new javax.swing.JLabel();
        txtfieldPersonID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtfieldName = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        txtfieldRole = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtfieldEmail = new javax.swing.JTextField();
        BlockCheckBox = new javax.swing.JCheckBox();
        lblBlock = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        bthSearch = new javax.swing.JButton();
        img1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        GOp.setBackground(new java.awt.Color(255, 255, 255));
        GOp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GOp.setText("Technology Provider");

        GridOperatorName.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        GridOperatorName.setText("Name");

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Settings");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("logout");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GOp, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(GridOperatorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 587, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GOp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton10)
                        .addComponent(btnBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GridOperatorName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        DashBoard.setBackground(new java.awt.Color(255, 255, 255));

        lblEnergyProducers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnergyProducers.setText("Total Energy Procured");

        lblEnergyProducersVal.setBackground(new java.awt.Color(153, 255, 255));
        lblEnergyProducersVal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEnergyProducersVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnergyProducersVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblEnergyProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnergyProd.setText("Total Energy Available");

        lblEnergyProdVal.setBackground(new java.awt.Color(153, 255, 255));
        lblEnergyProdVal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEnergyProdVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnergyProdVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblConsumers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsumers.setText("Total Consumers");

        lblConsumersVal.setBackground(new java.awt.Color(153, 255, 255));
        lblConsumersVal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConsumersVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsumersVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblConsumptionVal.setBackground(new java.awt.Color(153, 255, 255));
        lblConsumptionVal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConsumptionVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsumptionVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblConsumption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsumption.setText("Total Consumption");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DashBoardLayout = new javax.swing.GroupLayout(DashBoard);
        DashBoard.setLayout(DashBoardLayout);
        DashBoardLayout.setHorizontalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnergyProducersVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEnergyProducers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConsumersVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConsumers, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConsumptionVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConsumption, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(lblEnergyProdVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEnergyProd))
                .addGap(64, 64, 64)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        DashBoardLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblConsumers, lblConsumersVal, lblConsumption, lblConsumptionVal, lblEnergyProd, lblEnergyProdVal, lblEnergyProducers, lblEnergyProducersVal});

        DashBoardLayout.setVerticalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DashBoardLayout.createSequentialGroup()
                            .addComponent(lblEnergyProd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblEnergyProdVal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(lblConsumption, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblConsumptionVal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(DashBoardLayout.createSequentialGroup()
                            .addComponent(lblEnergyProducers, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblEnergyProducersVal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(lblConsumers, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblConsumersVal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        DashBoardLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblConsumersVal, lblConsumptionVal, lblEnergyProdVal, lblEnergyProducersVal});

        jTabbedPane1.addTab("Dashboard", DashBoard);

        Support.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Help ID", "Issue Raised by", "Description"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Date");

        jLabel2.setText("Help ID");

        jLabel3.setText("Issue Raised by");

        jLabel4.setText("Issue Description");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout SupportLayout = new javax.swing.GroupLayout(Support);
        Support.setLayout(SupportLayout);
        SupportLayout.setHorizontalGroup(
            SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupportLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(SupportLayout.createSequentialGroup()
                        .addGroup(SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SupportLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(SupportLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(SupportLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SupportLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        SupportLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        SupportLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane2, jTextField1, jTextField2, jTextField3});

        SupportLayout.setVerticalGroup(
            SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SupportLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton1))
                    .addGroup(SupportLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 120, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Support", Support);

        Reports.setBackground(new java.awt.Color(255, 255, 255));

        ReportsTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        ReportsTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        ProductionReport.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Source of Energy", "Quantity Procured"
            }
        ));
        jScrollPane6.setViewportView(jTable4);

        btnExport3.setBackground(new java.awt.Color(0, 0, 0));
        btnExport3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExport3.setForeground(new java.awt.Color(255, 255, 255));
        btnExport3.setText("Export");

        javax.swing.GroupLayout ProductionReportLayout = new javax.swing.GroupLayout(ProductionReport);
        ProductionReport.setLayout(ProductionReportLayout);
        ProductionReportLayout.setHorizontalGroup(
            ProductionReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductionReportLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(ProductionReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExport3))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        ProductionReportLayout.setVerticalGroup(
            ProductionReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductionReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExport3)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        ReportsTabbedPane.addTab("Production", ProductionReport);

        ConsumptionReport.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane12.setBackground(new java.awt.Color(255, 255, 255));

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Consumers", "Energy Consumption"
            }
        ));
        jScrollPane12.setViewportView(jTable9);

        btnExport5.setBackground(new java.awt.Color(0, 0, 0));
        btnExport5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExport5.setForeground(new java.awt.Color(255, 255, 255));
        btnExport5.setText("Export");

        javax.swing.GroupLayout ConsumptionReportLayout = new javax.swing.GroupLayout(ConsumptionReport);
        ConsumptionReport.setLayout(ConsumptionReportLayout);
        ConsumptionReportLayout.setHorizontalGroup(
            ConsumptionReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsumptionReportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsumptionReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExport5)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        ConsumptionReportLayout.setVerticalGroup(
            ConsumptionReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsumptionReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExport5)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        ReportsTabbedPane.addTab("Consumption", ConsumptionReport);

        Forecast.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("From Date");

        jLabel19.setText("To Date");

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Forecast");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Forecasted Production"
            }
        ));
        jScrollPane5.setViewportView(jTable7);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("View as Graphs");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel20.setText("Production Forecast");

        jLabel21.setText("Consumption Forecast");

        jScrollPane11.setBackground(new java.awt.Color(255, 255, 255));

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Forecasted Consumption"
            }
        ));
        jScrollPane11.setViewportView(jTable8);

        javax.swing.GroupLayout ForecastLayout = new javax.swing.GroupLayout(Forecast);
        Forecast.setLayout(ForecastLayout);
        ForecastLayout.setHorizontalGroup(
            ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForecastLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ForecastLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ForecastLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7))
                    .addGroup(ForecastLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        ForecastLayout.setVerticalGroup(
            ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForecastLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton7))
                    .addGroup(ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jDateChooser8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ForecastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        ReportsTabbedPane.addTab("ForeCast", Forecast);

        Graphs.setBackground(new java.awt.Color(255, 255, 255));

        Graph2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        Graph2.addTab("Graphs1", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        Graph2.addTab("Graphs2", jPanel4);

        javax.swing.GroupLayout GraphsLayout = new javax.swing.GroupLayout(Graphs);
        Graphs.setLayout(GraphsLayout);
        GraphsLayout.setHorizontalGroup(
            GraphsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Graph2)
        );
        GraphsLayout.setVerticalGroup(
            GraphsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Graph2)
        );

        ReportsTabbedPane.addTab("Graphs", Graphs);

        javax.swing.GroupLayout ReportsLayout = new javax.swing.GroupLayout(Reports);
        Reports.setLayout(ReportsLayout);
        ReportsLayout.setHorizontalGroup(
            ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ReportsTabbedPane))
        );
        ReportsLayout.setVerticalGroup(
            ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ReportsTabbedPane))
        );

        jTabbedPane1.addTab("Reports", Reports);

        ManageUsers.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Search by Any");

        TableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "User ID", "Name", "Role"
            }
        ));
        jScrollPane3.setViewportView(TableUsers);

        btnView.setBackground(new java.awt.Color(0, 0, 0));
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblPersonID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonID.setText("Person ID");

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name");

        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole.setText("Role");

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email");

        lblBlock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBlock.setText("Block");

        btnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        bthSearch.setBackground(new java.awt.Color(0, 0, 0));
        bthSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bthSearch.setForeground(new java.awt.Color(255, 255, 255));
        bthSearch.setText("Search");
        bthSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bthSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageUsersLayout = new javax.swing.GroupLayout(ManageUsers);
        ManageUsers.setLayout(ManageUsersLayout);
        ManageUsersLayout.setHorizontalGroup(
            ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageUsersLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageUsersLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(bthSearch)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ManageUsersLayout.createSequentialGroup()
                        .addGroup(ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPersonID, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(lblBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfieldPersonID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BlockCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addGroup(ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManageUsersLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfieldRole, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83)
                                .addComponent(btnView))
                            .addGroup(ManageUsersLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnSubmit)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        ManageUsersLayout.setVerticalGroup(
            ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bthSearch))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(lblPersonID)
                    .addComponent(txtfieldPersonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole)
                    .addComponent(txtfieldRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtfieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(txtfieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageUsersLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnSubmit))
                    .addGroup(ManageUsersLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManageUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BlockCheckBox)
                            .addComponent(lblBlock))))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Users", ManageUsers);

        jSplitPane1.setRightComponent(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            // Assuming your table model has the date, ID, raised by, and description in columns 0-3 respectively
            HelpRequest h = (HelpRequest) jTable1.getModel().getValueAt(selectedRow, 1);
            

            jTextField1.setText(h.getDate().toString());
            jTextField2.setText(h.getHelpID().toString());
            jTextField3.setText(h.getRaisedby());
            jTextArea1.setText(h.getDescription());
        } else {
            // No row is selected
            JOptionPane.showMessageDialog(null, "Please select a row to view details.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        AccInfoUpdateJPanel accCreationPanel = new AccInfoUpdateJPanel(cardLayout, business, user);
        cardLayout.add("AccInfoUpdateJPanel", accCreationPanel);
        CardLayout layout = (CardLayout) cardLayout.getLayout();
        layout.next(cardLayout);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        cardLayout.remove(this);
        CardLayout layout = (CardLayout) cardLayout.getLayout();
        layout.previous(cardLayout);
    }//GEN-LAST:event_btnBackActionPerformed

    private void populateForecastTable(List<EnergyData> forecastedData) {
        DefaultTableModel model = (DefaultTableModel) jTable7.getModel(); // Replace jTableForecast with your actual table name
        model.setRowCount(0); // Clear existing data

        for (EnergyData data : forecastedData) {
           Object[] row = new Object[3]; 
            row[0] = data.getTimestamp().toLocalDate(); 
            row[1] = data.getEnergyOutput();
            model.addRow(row);
        }
    }
        
            private void populateForecastTable(Map<LocalDate, Double> m) {
        DefaultTableModel model = (DefaultTableModel) jTable8.getModel();
        model.setRowCount(0); // Clear existing data

        for (Map.Entry<LocalDate, Double> entry : m.entrySet()) {
            LocalDate date = entry.getKey();
            Double value = entry.getValue();
            Object[] row = new Object[2];
                row[0] = date;
                row[1] = value;
            model.addRow(row);
        }
        
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        List<EnergyData> historicalData = new ArrayList<>();
       for(EnergyProducer ep : business.getEnergyProducers().getAllProducers()){
           for(EnergyData ed : ep.getEdc().getEnergyDataList()){
            historicalData.add(ed);
           }
       }
        System.out.println("frocast "+historicalData.size());
        
        // Forecast future production based on the average
        LocalDate startDate = jDateChooser7.getDate().toInstant()
        .atZone(ZoneId.systemDefault())
        .toLocalDate(); // get start date from "From Date" date chooser

        LocalDate endDate = jDateChooser8.getDate().toInstant()
        .atZone(ZoneId.systemDefault())
        .toLocalDate();// get end date from "To Date" date chooser
        
        List<EnergyData> forecastedData = ForecastingUtil.forecastProduction(historicalData, startDate, endDate, null, "defaultLocation", "defaultSource");
        ChartPanel chartPanel2 = ChartUtils.createLineChartPanel(forecastedData);
        
        Map<LocalDate, Double> m  = ForecastingUtil.forecastAllConsumerDemand(business.getGridData().getCt(), startDate, endDate);
        JFreeChart chart = ChartUtils.createLineChart(m);

// Create a panel to display the chart
        ChartPanel chartPanel1 = new ChartPanel(chart);
        // Assuming 'this' is a JPanel, you add the chartPanel to it
        containerPanel.removeAll();
    
    // Set the layout
        // Set preferred sizes for both chart panels
    Dimension chartSize = new Dimension(500, 400); // Set your desired size
    chartPanel1.setPreferredSize(chartSize);
    chartPanel2.setPreferredSize(chartSize);

    // Create a container panel

    // Set the layout to GridLayout for equal sizing
    containerPanel.setLayout(new GridLayout(1, 2)); // 1 row, 2 columns

    // Add both chart panels to the container
    containerPanel.add(chartPanel1);
    containerPanel.add(chartPanel2);

    // Display the container panel in a JOptionPane
    
        populateForecastTable(forecastedData);
        populateForecastTable(m);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JOptionPane optionPane = new JOptionPane(containerPanel, JOptionPane.PLAIN_MESSAGE);
    JDialog dialog = optionPane.createDialog("Forecasting Charts");
    dialog.setSize(950, 650); // Set dialog size
    dialog.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        int selectedRow = TableUsers.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select a Row", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            UserAccount ua = (UserAccount) TableUsers.getValueAt(selectedRow, 0);

            txtfieldEmail.setText(ua.getAssociatedPersonProfile().getPerson().getEmail());
            txtfieldName.setText(ua.getAssociatedPersonProfile().getPerson().getName());
            txtfieldPersonID.setText(String.valueOf(ua.getAssociatedPersonProfile().getPerson().getPersonId()));
            txtfieldRole.setText(ua.getAssociatedPersonProfile().getRole());
            BlockCheckBox.setSelected(!ua.isEnabled());
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        int selectedRow = TableUsers.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select a Row", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            UserAccount ua = (UserAccount) TableUsers.getValueAt(selectedRow, 0);

            ua.setEnabled(!BlockCheckBox.isSelected());
            JOptionPane.showMessageDialog(this, "Submitted!" );
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void bthSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthSearchActionPerformed
        ArrayList<UserAccount> users = new ArrayList();
        try{
            if(business.getUserAcconts().findUserAccount(Integer.parseInt(txtSearch.getText()))!=null){
                users.add(business.getUserAcconts().findUserAccount(Integer.parseInt(txtSearch.getText())));
                populateManageTable(users);
            }
        }catch(Exception e){

        }
        if(!business.getUserAcconts().getUsersByName(txtSearch.getText()).isEmpty()){
            users.addAll(business.getUserAcconts().getUsersByName(txtSearch.getText()));
            populateManageTable(users);
        }else{
            JOptionPane.showMessageDialog(this, "No course Found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bthSearchActionPerformed
    
    public void populateHelpRequestsTable(JTable table, List<HelpRequest> helpRequestsList) {
    // Create a table model. The column names should match the data you want to display.
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear the existing rows
        // Add rows to the model
        for (HelpRequest request : helpRequestsList) {
            model.addRow(new Object[]{
                request.getDate(), // Assuming getDate() returns a LocalDate
                request,
                request.getRaisedby(),
                request.getDescription()
            });
        }

        // Set the model to the table
        jTable1.setModel(model);
    }

    
    public void populateProcuredTable() {
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        model.setRowCount(0); // Clear the existing rows


            List<Transaction> transactions = business.getGridData().getTc().getAllTransactions();

            // Iterate over the transactions and add them to the table model
            for (Transaction transaction : transactions) {
                Object[] row = new Object[2]; // Adjust the size based on the number of columns in your table
                row[0] = transaction.getEnergySource();
                row[1] = transaction.getAmountSold();

                model.addRow(row);
            }

        jTable4.setModel(model);
        ChartPanel chartPanel = ChartUtils.createEnergySourcePieChart(business.getEnergyProducers());

        // Assuming 'this' is a JPanel, you add the chartPanel to it
        jPanel3.setLayout(new BorderLayout());
        jPanel3.add(chartPanel, BorderLayout.CENTER);

        // Revalidate and repaint to ensure the chart is displayed
        jPanel3.revalidate();
        jPanel3.repaint();
    }
    
    public void populateConsumedTable() {
        DefaultTableModel model = (DefaultTableModel) jTable9.getModel();
        model.setRowCount(0); // Clear the existing rows


            List<ConsumerTransaction> transactions = business.getGridData().getCt();

            // Iterate over the transactions and add them to the table model
            for (ConsumerTransaction transaction : transactions) {
                Object[] row = new Object[2]; // Adjust the size based on the number of columns in your table
                row[0] = transaction.getConsumerId();
                row[1] = transaction.getQuantityOfEnergy();

                model.addRow(row);
            }

        jTable9.setModel(model);
        ChartPanel chartPanel = ChartUtils.createEnergySourceChart(business.getGridData().getTc().getAllTransactions());

        // Assuming 'this' is a JPanel, you add the chartPanel to it
        jPanel4.setLayout(new BorderLayout());
        jPanel4.add(chartPanel, BorderLayout.CENTER);

        // Revalidate and repaint to ensure the chart is displayed
        jPanel4.revalidate();
        jPanel4.repaint();
    }
    
    private void gridDashboard(){
        Double totalProcured = business.getGridData().calculateTotalEnergyProcured();
        Double totalConsumed = business.getGridData().calculateTotalEnergyConsumered();
        lblEnergyProducersVal.setText(String.valueOf(totalProcured));
        lblConsumptionVal.setText(String.valueOf(totalConsumed));
        
        lblEnergyProdVal.setText(String.valueOf(totalProcured-totalConsumed));
        
        lblConsumersVal.setText(String.valueOf(business.getGridData().findTotalConsumers()));
        populatePieGraph();
    }
    
    private void populatePieGraph() {
        Map<String, Double> aggregatedData = business.getGridData().aggregateAmountSoldByEnergySource();
        
        JFreeChart chart = ChartUtils.createPieChart(aggregatedData);

// Create a panel to display the chart
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(370, 370));  // You can adjust the size
        
        // Assuming 'this' is a JPanel, you add the chartPanel to it
        jPanel5.setLayout(new BorderLayout());
        jPanel5.add(chartPanel, BorderLayout.CENTER);

        // Revalidate and repaint to ensure the chart is displayed
        jPanel5.revalidate();
        jPanel5.repaint();
    }

        private void populateManageTable(ArrayList<UserAccount> users) {
        
        //users.addAll(business.getUserAcconts().getUserAccountList());
        DefaultTableModel model = (DefaultTableModel) TableUsers.getModel();
        model.setRowCount(0);
         
        for(UserAccount u : users){
             
            Object[] row = new Object[5];
            row[0] = u;
            row[1] = u.getAssociatedPersonProfile().getPerson().getName();
            row[2] = u.getAssociatedPersonProfile().getRole();
            
            model.addRow(row);
                            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BlockCheckBox;
    private javax.swing.JPanel ConsumptionReport;
    private javax.swing.JPanel DashBoard;
    private javax.swing.JPanel Forecast;
    private javax.swing.JLabel GOp;
    private javax.swing.JTabbedPane Graph2;
    private javax.swing.JPanel Graphs;
    private javax.swing.JLabel GridOperatorName;
    private javax.swing.JPanel ManageUsers;
    private javax.swing.JPanel ProductionReport;
    private javax.swing.JPanel Reports;
    private javax.swing.JTabbedPane ReportsTabbedPane;
    private javax.swing.JPanel Support;
    private javax.swing.JTable TableUsers;
    private javax.swing.JButton bthSearch;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExport3;
    private javax.swing.JButton btnExport5;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel img1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser7;
    private com.toedter.calendar.JDateChooser jDateChooser8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblBlock;
    private javax.swing.JLabel lblConsumers;
    private javax.swing.JLabel lblConsumersVal;
    private javax.swing.JLabel lblConsumption;
    private javax.swing.JLabel lblConsumptionVal;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnergyProd;
    private javax.swing.JLabel lblEnergyProdVal;
    private javax.swing.JLabel lblEnergyProducers;
    private javax.swing.JLabel lblEnergyProducersVal;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPersonID;
    private javax.swing.JLabel lblRole;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtfieldEmail;
    private javax.swing.JTextField txtfieldName;
    private javax.swing.JTextField txtfieldPersonID;
    private javax.swing.JTextField txtfieldRole;
    // End of variables declaration//GEN-END:variables
}
